"""Derive a local denylist ("fingerprint") from the private data directory.

The public-repository scanner can only catch private data it knows about. This
module reads the owner's private data directory and writes distinctive terms to
`~/.lce-private/denylist.generated.txt` (outside every repository, never
committed). `lce privacy-scan` then flags them in the working tree and, with
`--history`, in every commit reachable from any ref.

Derived terms (all from the private data directory, nothing hard-coded):
- cadence slot tokens as they appear in slot/job ids, e.g. `<day>-<HHMM>`;
- profile identity: display name, current role, headlines, positioning,
  LinkedIn profile path;
- stories: story id, title, sensitive terms;
- posts: post id and the opening line of each draft/post and of imported
  published posts.

The generated list is used by the repository scanner only, never by post QA
(the owner's own posts naturally contain their own opening lines).
Only counts are ever printed, never terms.
"""

from __future__ import annotations

import os
from pathlib import Path

from lce.store import DataStore

GENERATED_PATH = "~/.lce-private/denylist.generated.txt"
MIN_LEN = 6          # shorter terms are too generic to flag reliably
MIN_LINE_LEN = 24    # opening lines shorter than this are not distinctive
HEADER = ("# Generated by `lce privacy-denylist` from the private data directory.\n"
          "# Local only; never commit. Regenerate after changing private data.\n")


def generated_path() -> Path:
    return Path(os.environ.get("LCE_DENYLIST_GENERATED_PATH") or GENERATED_PATH).expanduser()


def _first_line(text: str | None) -> str | None:
    for line in (text or "").splitlines():
        line = line.strip()
        if line:
            return line if len(line) >= MIN_LINE_LEN else None
    return None


def _slot_tokens(settings: dict) -> list[str]:
    tokens = []
    for slot in ((settings.get("cadence") or {}).get("slots") or []):
        day, time = str(slot.get("day", "")).lower(), str(slot.get("time", ""))
        hh, _, mm = time.partition(":")
        if day and hh.isdigit() and mm.isdigit():
            tokens.append(f"{day}-{int(hh):02d}{int(mm):02d}")
    return tokens


def derive_terms(store: DataStore) -> list[str]:
    terms: list[str] = list(_slot_tokens(store.settings()))

    profile = store.profile() or {}
    ident = profile.get("identity") or {}
    linkedin = profile.get("linkedin") or {}
    terms += [ident.get("display_name"), ident.get("current_role"), ident.get("headline"),
              linkedin.get("headline"), profile.get("positioning")]
    url = linkedin.get("profile_url") or ""
    if "linkedin.com/" in url:
        terms.append(url.split("linkedin.com/", 1)[1].strip("/"))

    for story_id, story in store.stories().items():
        terms += [story_id, story.get("title"), *(story.get("sensitive_terms") or [])]

    for post_id in store.post_ids():
        terms.append(post_id)
        terms.append(_first_line(store.post_text(post_id, "post.md")
                                 or store.post_text(post_id, "draft.md")))
    terms += [_first_line(t) for t in store.external_posts().values()]

    out, seen = [], set()
    for t in terms:
        t = " ".join(str(t).split()) if t else ""
        if len(t) >= MIN_LEN and t.lower() not in seen:
            seen.add(t.lower())
            out.append(t)
    return sorted(out, key=str.lower)


def write_generated(store: DataStore, path: Path | None = None) -> tuple[Path, int]:
    path = path or generated_path()
    terms = derive_terms(store)
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(HEADER + "".join(f"{t}\n" for t in terms), encoding="utf-8")
    tmp.chmod(0o600)
    tmp.replace(path)
    return path, len(terms)
